In [7]:
import numpy as np
oneDarray=np.array([1,2,3,4])
oneDarray


array([1, 2, 3, 4])

In [18]:
oneDarray.size


4

In [19]:
oneDarray.itemsize

8

In [11]:
oneDarray.dtype

dtype('int64')

In [28]:
oneDarray.astype('float')

array([1., 2., 3., 4.])

In [29]:
twoDarray=np.array([[1,2,3],[4,5,6]])

In [30]:
twoDarray


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
twoDarray.dtype

dtype('int64')

In [26]:
twoDarray.itemsize

8

In [35]:
twoDarray.itemsize

8

In [32]:
twoDarray.astype (float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
twoDarray.shape

(2, 3)

In [33]:
twoDarray.size


6

In [34]:
twoDarray.itemsize

8

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [46]:
np.linspace(10,20,9)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])