In [1]:
import numpy as np


In [9]:
arr1=np.array([2,4,6,8,10])
arr2=np.array([1,3,5,7,9])
#vector multiply
arr1*arr2

array([ 2, 12, 30, 56, 90])

In [10]:
arr1-arr2

array([1, 1, 1, 1, 1])

In [11]:
arr1+arr2

array([ 3,  7, 11, 15, 19])

In [8]:
#scaler multiply
arr3=arr1*3

array([ 6, 12, 18, 24, 30])

In [47]:
#tell where the value is more then 6 in arr2
arr2>6
arr4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [45]:
#dot product 
arr4=np.arange(8).reshape(4,2)
arr5=np.arange(0,16).reshape(2,8)
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [46]:
arr4.dot(arr5)


array([[  8,   9,  10,  11,  12,  13,  14,  15],
       [ 24,  29,  34,  39,  44,  49,  54,  59],
       [ 40,  49,  58,  67,  76,  85,  94, 103],
       [ 56,  69,  82,  95, 108, 121, 134, 147]])

In [48]:
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [49]:
arr5.min()

np.int64(0)

In [53]:
#max values i colums 
arr6=np.array ([[5,9,3,6,8],[3,10,2,13,5]])
arr6.max(axis=0)

array([ 5, 10,  3, 13,  8])

In [55]:
#row wise max value
arr6.max(axis=1)

array([ 9, 13])

In [63]:
#horizontal stack
np.hstack((arr1,arr2))

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [65]:
np.vstack((arr1,arr2))

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [66]:
arr1


array([ 2,  4,  6,  8, 10])

In [67]:
arr2

array([1, 3, 5, 7, 9])

In [68]:
arr4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [85]:
arr8=np.arange(8,16).reshape(4,2)

In [86]:
arr8

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [87]:
np.hstack((arr4,arr8))

array([[ 0,  1,  8,  9],
       [ 2,  3, 10, 11],
       [ 4,  5, 12, 13],
       [ 6,  7, 14, 15]])

In [88]:
np.vstack((arr4,arr8))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [92]:
np.hsplit(arr4,2)

[array([[0],
        [2],
        [4],
        [6]]),
 array([[1],
        [3],
        [5],
        [7]])]

In [95]:
np.vsplit(arr8,4)

[array([[8, 9]]), array([[10, 11]]), array([[12, 13]]), array([[14, 15]])]

In [106]:
#non static function
arr5.sum()

np.int64(120)

In [107]:
arr8.sum(axis=1)

array([17, 21, 25, 29])

In [108]:
arr8.sum(axis=0)

array([44, 48])

In [109]:
#static functions of numpy
np.median(arr8)

np.float64(11.5)

In [110]:
np.exp(arr8)

array([[2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06]])

In [111]:
np.sin(arr8)

array([[ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021],
       [-0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784]])

In [105]:
arr8.std()

np.float64(2.29128784747792)